apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  project: infra
  source:
    chart: victoria-metrics-k8s-stack
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.28.2
    helm:
      releaseName: victoriametrics
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
