{{- if .Values.gitops.argocd.enabled }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: {{ .Values.clusterName }}-argocd
  namespace: {{ .Values.targetNamespace | default "default" }}
spec:
  clusterSelector:
    matchLabels:
      argoCDChart: enabled
  repoURL: https://argoproj.github.io/argo-helm
  chartName: argo-cd
  version: {{ .Values.gitops.argocd.version }}
  namespace: {{ .Values.gitops.argocd.namespace | default "argocd" }}
  options:
    waitForJobs: true
    wait: true
    install:
      createNamespace: true
    upgrade:
      maxHistory: 10
  valuesTemplate: |
    global:
      domain: argocd.{{ "{{" }} .Cluster.metadata.name {{ "}}" }}.local
    configs:
      secret:
        argocdServerAdminPassword: {{ .Values.gitops.argocd.adminPassword | quote }}
    server:
      service:
        type: {{ .Values.gitops.argocd.server.service.type | default "ClusterIP" }}
      ingress:
        enabled: false
    dex:
      enabled: false
    redis:
      enabled: true
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
    repoServer:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
    applicationSet:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
    notifications:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
{{- end }}
