{{- if .Values.addons.argocd.enabled }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: {{ .Values.clusterName }}-argocd
  namespace: {{ .Values.targetNamespace | default "default" }}
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .Values.clusterName }}
      deploy-argocd: "true"
  repoURL: https://argoproj.github.io/argo-helm
  chartName: argo-cd
  version: {{ .Values.addons.argocd.version }}
  targetNamespace: {{ .Values.addons.argocd.namespace }}
  createNamespace: true
  valuesTemplate: |
    global:
      domain: argocd.{{ "{{" }} .Cluster.metadata.name {{ "}}" }}.local

    configs:
      secret:
        argocdServerAdminPassword: {{ .Values.addons.argocd.adminPassword | quote }}
    server:
      service:
        type: {{ .Values.addons.argocd.server.service.type }}
        {{- if eq .Values.addons.argocd.server.service.type "LoadBalancer" }}
        annotations:
          metallb.universe.tf/address-pool: default
        {{- end }}
      ingress:
        enabled: false
    dex:
      enabled: false
    redis:
      enabled: true
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
    repoServer:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
    server:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
{{- end }}
