apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.targetNamespace | default "default" }}
  {{- if .Values.gitops.argocd.enabled }}
  labels:
    argoCDChart: enabled
  {{- end }}
spec:
  controlPlaneEndpoint:
    host: {{ .Values.network.vip }}
    port: 6443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: {{ .Values.clusterName }}-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxCluster
    name: {{ .Values.clusterName }}
