{{- $controlPlaneCount := 0 }}
{{- $workerCount := 0 }}
{{- range .Values.nodes }}
  {{- if eq .type "control-plane" }}
    {{- $controlPlaneCount = add $controlPlaneCount 1 }}
  {{- else if eq .type "worker" }}
    {{- $workerCount = add $workerCount 1 }}
  {{- end }}
{{- end }}

{{- $controlPlaneIndex := 0 }}
{{- $workerIndex := 0 }}
{{- range .Values.nodes }}

{{- if eq .type "control-plane" }}
{{- $controlPlaneIndex = add $controlPlaneIndex 1 }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachine
metadata:
  name: {{ $.Values.clusterName }}-cp-{{ $controlPlaneIndex }}
  namespace: {{ $.Values.targetNamespace | default "default" }}
spec:
  disks:
    bootVolume:
      disk: scsi0
      sizeGb: {{ index $.Values.nodeDefaults "control-plane" "disk" }}
  format: qcow2
  full: true
  memoryMiB: {{ index $.Values.nodeDefaults "control-plane" "memory" }}
  network:
    default:
      bridge: {{ $.Values.network.bridge }}
      model: virtio
      vlan: {{ $.Values.network.vlan }}
  numCores: {{ index $.Values.nodeDefaults "control-plane" "cores" }}
  numSockets: 1
  sourceNode: {{ $.Values.proxmox.node }}
  templateID: {{ $.Values.proxmox.templateId }}
{{- if .vmID }}
  virtualMachineID: {{ .vmID }}
{{- else }}
  vmIDRange:
    start: {{ (splitList "-" $.Values.proxmox.vmIdRange) | first }}
    end: {{ (splitList "-" $.Values.proxmox.vmIdRange) | last }}
{{- end }}
  checks:
    skipCloudInitStatus: true
    skipQemuGuestAgent: true
  metadataSettings:
    providerIDInjection: true
  tags:
    - {{ $.Values.clusterName }}
    - {{ $.Values.clusterName }}-control-plane
    - {{ .ip }}
{{- range $.Values.extraTags }}
    - {{ . }}
{{- end }}

---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfig
metadata:
  name: {{ $.Values.clusterName }}-cp-{{ $controlPlaneIndex }}
  namespace: {{ $.Values.targetNamespace | default "default" }}
spec:
  generateType: controlplane
  strategicPatches:
    - |
      - op: replace
        path: /machine/install
        value:
          disk: /dev/sda
          extensions:
            - image: ghcr.io/siderolabs/qemu-guest-agent:9.2.0
      - op: add
        path: /machine/install/extraKernelArgs
        value:
          - net.ifnames=0
      - op: add
        path: /machine/network/nameservers
        value:
{{- range $.Values.network.dnsServers }}
          - {{ . }}
{{- end }}
      - op: add
        path: /machine/network/disableSearchDomain
        value: true
      - op: add
        path: /machine/network/interfaces
        value:
          - interface: eth0
            dhcp: false
            addresses:
              - {{ .ip }}/24
            routes:
              - network: 0.0.0.0/0
                gateway: {{ $.Values.network.gateway }}
            vip:
              ip: {{ $.Values.network.vip }}
      - op: add
        path: /cluster/externalCloudProvider
        value:
          enabled: true
          manifests:
            - https://raw.githubusercontent.com/siderolabs/talos-cloud-controller-manager/main/docs/deploy/cloud-controller-manager.yml
            - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          cloud-provider: external
          rotate-server-certificates: "true"
      - op: add
        path: /machine/features/kubernetesTalosAPIAccess
        value:
          enabled: true
          allowedRoles:
            - os:reader
          allowedKubernetesNamespaces:
            - kube-system

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: {{ $.Values.clusterName }}-cp-{{ $controlPlaneIndex }}
  namespace: {{ $.Values.targetNamespace | default "default" }}
  labels:
    cluster.x-k8s.io/cluster-name: {{ $.Values.clusterName }}
    cluster.x-k8s.io/control-plane: ""
spec:
  clusterName: {{ $.Values.clusterName }}
  version: {{ $.Values.kubernetes.version }}
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
      kind: TalosConfig
      name: {{ $.Values.clusterName }}-cp-{{ $controlPlaneIndex }}
      namespace: {{ $.Values.targetNamespace | default "default" }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxMachine
    name: {{ $.Values.clusterName }}-cp-{{ $controlPlaneIndex }}
    namespace: {{ $.Values.targetNamespace | default "default" }}

{{- else if eq .type "worker" }}
{{- $workerIndex = add $workerIndex 1 }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachine
metadata:
  name: {{ $.Values.clusterName }}-worker-{{ $workerIndex }}
  namespace: {{ $.Values.targetNamespace | default "default" }}
spec:
  disks:
    bootVolume:
      disk: scsi0
      sizeGb: {{ $.Values.nodeDefaults.worker.disk }}
  format: qcow2
  full: true
  memoryMiB: {{ $.Values.nodeDefaults.worker.memory }}
  network:
    default:
      bridge: {{ $.Values.network.bridge }}
      model: virtio
      vlan: {{ $.Values.network.vlan }}
  numCores: {{ $.Values.nodeDefaults.worker.cores }}
  numSockets: 1
  sourceNode: {{ $.Values.proxmox.node }}
  templateID: {{ $.Values.proxmox.templateId }}
{{- if .vmID }}
  virtualMachineID: {{ .vmID }}
{{- else }}
  vmIDRange:
    start: {{ (splitList "-" $.Values.proxmox.vmIdRange) | first }}
    end: {{ (splitList "-" $.Values.proxmox.vmIdRange) | last }}
{{- end }}
  checks:
    skipCloudInitStatus: true
    skipQemuGuestAgent: true
  metadataSettings:
    providerIDInjection: true
  tags:
    - {{ $.Values.clusterName }}
    - {{ $.Values.clusterName }}-worker
    - {{ .ip }}
{{- range $.Values.extraTags }}
    - {{ . }}
{{- end }}

---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfig
metadata:
  name: {{ $.Values.clusterName }}-worker-{{ $workerIndex }}
  namespace: {{ $.Values.targetNamespace | default "default" }}
spec:
  generateType: worker
  strategicPatches:
    - |
      - op: replace
        path: /machine/install
        value:
          disk: /dev/sda
          extensions:
            - image: ghcr.io/siderolabs/qemu-guest-agent:9.2.0
      - op: add
        path: /machine/install/extraKernelArgs
        value:
          - net.ifnames=0
      - op: add
        path: /machine/network/nameservers
        value:
{{- range $.Values.network.dnsServers }}
          - {{ . }}
{{- end }}
      - op: add
        path: /machine/network/disableSearchDomain
        value: true
      - op: add
        path: /machine/network/interfaces
        value:
          - interface: eth0
            dhcp: false
            addresses:
              - {{ .ip }}/24
            routes:
              - network: 0.0.0.0/0
                gateway: {{ $.Values.network.gateway }}
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          cloud-provider: external
          rotate-server-certificates: "true"

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: {{ $.Values.clusterName }}-worker-{{ $workerIndex }}
  namespace: {{ $.Values.targetNamespace | default "default" }}
  labels:
    cluster.x-k8s.io/cluster-name: {{ $.Values.clusterName }}
    node-role.kubernetes.io/worker: ""
spec:
  clusterName: {{ $.Values.clusterName }}
  version: {{ $.Values.kubernetes.version }}
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
      kind: TalosConfig
      name: {{ $.Values.clusterName }}-worker-{{ $workerIndex }}
      namespace: {{ $.Values.targetNamespace | default "default" }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxMachine
    name: {{ $.Values.clusterName }}-worker-{{ $workerIndex }}
    namespace: {{ $.Values.targetNamespace | default "default" }}

{{- end }}
{{- end }}