{{- $controlPlaneCount := 0 }}
{{- $singleNodeCount := 0 }}
{{- $workerCount := 0 }}
{{- range .Values.nodes }}
  {{- if eq .type "control-plane" }}
    {{- $controlPlaneCount = add $controlPlaneCount 1 }}
  {{- else if eq .type "single-node" }}
    {{- $singleNodeCount = add $singleNodeCount 1 }}
  {{- else if eq .type "worker-node" }}
    {{- $workerCount = add $workerCount 1 }}
  {{- end }}
{{- end }}

{{- if gt $workerCount 0 }}
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: {{ .Values.clusterName }}-workers
  namespace: {{ .Values.targetNamespace | default "default" }}
spec:
  template:
    spec:
      generateType: worker
      strategicPatches:
        - |
          - op: replace
            path: /machine/install
            value:
              disk: /dev/sda
              extensions:
                - image: ghcr.io/siderolabs/qemu-guest-agent:9.2.0
          - op: add
            path: /machine/install/extraKernelArgs
            value:
              - net.ifnames=0
          - op: add
            path: /machine/kubelet/extraArgs
            value:
              cloud-provider: external
              rotate-server-certificates: "true"
{{- end }}