apiVersion: v2
name: cluster-api-operator
description: A Helm chart for deploying ExternalSecrets-Operator in Kubernetes
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: cluster-api-operator
    repository: https://kubernetes-sigs.github.io/cluster-api-operator
    version: 0.16.0
