apiVersion: v2
name: cert-manager
description: A Helm chart for deploying cert-manager in Kubernetes
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.16.2
