apiVersion: v2
name: openbao
description: A Helm chart for deploying OpenBao (vault-fork) in Kubernetes
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: openbao
    repository: https://openbao.github.io/openbao-helm
    version: 0.7.0
