# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# The version of this blueprint, currently 1
version: 1
# Optional block of metadata, name is required if metadata is set
metadata:
  # Arbitrary key=value store, special labels are listed below
  labels:
    foo: bar
  name: example-blueprint
# Optional default context, instance context is merged over this.
context:
  foo: bar
# List of entries (required)
entries:
  - attrs:
      access_code_validity: minutes=1
      access_token_validity: minutes=5
      authorization_flow: dffb6385-b01e-4920-bf3a-5368dd77704e
      client_id: argocd
      client_secret: ""
      client_type: confidential
      include_claims_in_id_token: true
      invalidation_flow: a94ade3d-fe45-4c48-bf97-39a1f91609b1
      issuer_mode: per_provider
      name: ArgoCD
      property_mappings:
        - c7c8b771-1d1c-450f-8686-4bc48c53c189
        - 683ca8f8-f762-43b1-b6bd-2cc5d8687b7b
        - 1c8b5def-5aa5-4ede-89e7-b8b4c41d5fab
      redirect_uris:
        - matching_mode: strict
          url: https://argocd.simonoscar.me/api/dex/callback
        - matching_mode: strict
          url: http://localhost:8085/auth/callback
      refresh_token_validity: days=30
      signing_key: ba860676-85b2-41e1-98cb-71819d15881d
      sub_mode: hashed_user_id
    conditions: []
    identifiers:
      pk: 1
    model: authentik_providers_oauth2.oauth2provider
    permissions: []
    state: present
  - attrs:
      access_code_validity: minutes=1
      access_token_validity: minutes=5
      authorization_flow: dffb6385-b01e-4920-bf3a-5368dd77704e
      client_id: grafana
      client_secret: ""
      client_type: confidential
      include_claims_in_id_token: true
      invalidation_flow: a94ade3d-fe45-4c48-bf97-39a1f91609b1
      issuer_mode: per_provider
      name: Grafana
      property_mappings:
        - c7c8b771-1d1c-450f-8686-4bc48c53c189
        - 683ca8f8-f762-43b1-b6bd-2cc5d8687b7b
        - 1c8b5def-5aa5-4ede-89e7-b8b4c41d5fab
      redirect_uris:
        - matching_mode: strict
          url: https://grafana.simonoscar.me/login/generic_oauth
      refresh_token_validity: days=30
      signing_key: ba860676-85b2-41e1-98cb-71819d15881d
      sub_mode: hashed_user_id
    conditions: []
    identifiers:
      pk: 2
    model: authentik_providers_oauth2.oauth2provider
    permissions: []
    state: present
  - attrs:
      access_code_validity: minutes=1
      access_token_validity: minutes=5
      authorization_flow: dffb6385-b01e-4920-bf3a-5368dd77704e
      client_id: harbor
      client_secret: ""
      client_type: confidential
      include_claims_in_id_token: true
      invalidation_flow: a94ade3d-fe45-4c48-bf97-39a1f91609b1
      issuer_mode: per_provider
      name: Harbor
      property_mappings:
        - c7c8b771-1d1c-450f-8686-4bc48c53c189
        - 683ca8f8-f762-43b1-b6bd-2cc5d8687b7b
        - 1c8b5def-5aa5-4ede-89e7-b8b4c41d5fab
      redirect_uris:
        - matching_mode: strict
          url: https://harbor.simonoscar.me/c/oidc/callback
      refresh_token_validity: days=30
      signing_key: ba860676-85b2-41e1-98cb-71819d15881d
      sub_mode: hashed_user_id
    conditions: []
    identifiers:
      pk: 4
    model: authentik_providers_oauth2.oauth2provider
    permissions: []
    state: present
