apiVersion: v2
name: authentik
description: A Helm chart for deploying Authentik in Kubernetes
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: authentik
    repository: https://charts.goauthentik.io
    version: 2024.12.3
