apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-qa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    kargo.akuity.io/authorized-stage: infrastructure:qa
spec:
  project: infra
  source:
    repoURL: https://gitlab.com/simonoscr/gitops.git
    targetRevision: 59233eed7d0e56d4775a872af0d68adccda832cf
    path: infra/hello-world/qa
    helm:
      releaseName: hello-world-qa
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-stg-a
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    kargo.akuity.io/authorized-stage: infrastructure:stg-a
spec:
  project: infra
  source:
    repoURL: https://gitlab.com/simonoscr/gitops.git
    targetRevision: HEAD
    path: infra/hello-world/stg-a
    helm:
      releaseName: hello-world-stg-a
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world-stg-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-stg-b
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    kargo.akuity.io/authorized-stage: infrastructure:stg-b
spec:
  project: infra
  source:
    repoURL: https://gitlab.com/simonoscr/gitops.git
    targetRevision: HEAD
    path: infra/hello-world/stg-b
    helm:
      releaseName: hello-world-stg-b
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world-stg-b
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-stg-c
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    kargo.akuity.io/authorized-stage: infrastructure:stg-c
spec:
  project: infra
  source:
    repoURL: https://gitlab.com/simonoscr/gitops.git
    targetRevision: HEAD
    path: infra/hello-world/stg-c
    helm:
      releaseName: hello-world-stg-c
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world-stg-c
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
