apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-qa
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://gitlab.com/simonoscr/gitops.git
    targetRevision: HEAD
    path: infra/sealed-secrets/qa
    helm:
      releaseName: sealed-secrets-qa
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-stg
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://gitlab.com/simonoscr/gitops.git
    targetRevision: HEAD
    path: infra/sealed-secrets/stg
    helm:
      releaseName: sealed-secrets-stg
  destination:
    server: https://kubernetes.default.svc
    namespace: stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-prd
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://gitlab.com/simonoscr/gitops.git
    targetRevision: HEAD
    path: infra/sealed-secrets/prd
    helm:
      releaseName: sealed-secrets-prd
  destination:
    server: https://kubernetes.default.svc
    namespace: prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
