apiVersion: v2
name: sealed-secrets
description: A Helm chart for deploying Sealed-Secrets Controller in Kubernetes
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: sealed-secrets
    repository: https://bitnami-labs.github.io/sealed-secrets
    version: 2.11.0
