apiVersion: v2
name: oidc
description: A Helm chart for deploying VictoriaMetrics in Kubernetes
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: dex
    repository: https://charts.dexidp.io
    version: 0.19.1
