apiVersion: v2
name: tailscale-operator
description: A Helm chart for deploying Tailscale in Kubernetes
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: tailscale-operator
    repository: https://pkgs.tailscale.com/helmcharts
    version: 1.81.44
