{{- if .Values.policies.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-policies
data:
  {{- range $key, $value := .Values.policies.list }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
