apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: infra
  namespace: infra
spec:
  promotionPolicies:
    - stage: main
      autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: infrastructure
  namespace: infrastructure
spec:
  promotionPolicies:
    - stage: qa
      autoPromotionEnabled: true # auto-update in qa
    - stage: stg-a
      autoPromotionEnabled: true # auto-promote to stg
    - stage: stg-b
      autoPromotionEnabled: true # auto-promote to stg
    - stage: stg-c
      autoPromotionEnabled: true # auto-promote to stg
    - stage: prd-a
      autoPromotionEnabled: false # dont autopromote
    - stage: prd-b
      autoPromotionEnabled: false # dont autopromote
    - stage: prd-c
      autoPromotionEnabled: false # dont autopromote
