apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: infra-update-helm-dependency
  namespace: infrastructure
spec:
  vars:
    # Variables without a default value are required and must be provided when the task is referenced in a Promotion Template.
    - name: gitRepo
      value: git@gitlab.com:simonoscr/gitops.git
    - name: sourceBranch
      value: main
    - name: targetBranch
      value: ${{ vars.sourceBranch }}
    - name: chartRepo
      value: ${{ freight.contents["Warehouse/infrastructure-warehouse"].charts[vars.chartName].repoURL }}
    - name: chartName
      value: ${{ freight.contents["Warehouse/infrastructure-warehouse"].charts.keys[0] }}
    - name: chartDir
      value: ${{ vars.chartName }}
  steps:
    - uses: git-clone
      as: clone
      config:
        repoURL: ${{ vars.gitRepo }}
        checkout:
          - branch: ${{ vars.sourceBranch }}
            path: ./out
    ## OCI chartRepo
    #- uses: helm-update-chart
    #  as: update
    #  config:
    #    path: ./out/infra/${{ vars.chartDir }}/${{ ctx.stage }}
    #    charts:
    #      - repository: ${{ vars.chartRepo }}
    #        name: ${{ vars.chartName }}
    #        version: ${{ chartFrom(vars.chartRepo + "/" + vars.chartName).Version }}
    ## HTTPS chartRepo
    - uses: helm-update-chart
      as: update
      config:
        path: ./out/infra/${{ vars.chartDir }}/${{ ctx.stage }}
        charts:
          - repository: ${{ vars.chartRepo }}
            name: ${{ vars.chartName }}
            version: ${{ freight.contents["Warehouse/infrastructure-warehouse"].charts[vars.chartName].version }}
    - uses: git-commit
      as: commit
      config:
        path: ./out
        message: |
          ${{ vars.chartName }}(${{ ctx.stage }}): update helm-chart to ${{ freight.contents["Warehouse/infrastructure-warehouse"].charts[vars.chartName].version }}
    - uses: git-push
      as: push
      config:
        path: ./out
        branch: ${{ vars.targetBranch }}
