---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage-qa
  namespace: infrastructure
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: infrastructure-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: infrastructure-update-helm-chart-dep
          vars:
            chartDir: infra/hello-world
            chartName: nginx
            chartRepo: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage-stg
  namespace: infrastructure
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: infrastructure-warehouse
      sources:
        stages:
          - siko-qa
  promotionTemplate:
    spec:
      vars:
        - name: chartRepo
      steps:
        - task:
            name: infrastructure-update-helm-chart-dep
          vars:
            chartDir: infra/hello-world
            chartName: nginx
            chartRepo: oci://registry-1.docker.io/bitnamicharts
---
#apiVersion: kargo.akuity.io/v1alpha1
#kind: Stage
#metadata:
#  name: stage-qa
#  namespace: infrastructure
#spec:
#  requestedFreight:
#    - origin:
#        kind: Warehouse
#        name: infrastructure-warehouse
#      sources:
#        direct: true
#  promotionTemplate:
#    spec:
#      vars:
#        - name: chartRepo
#          value:
#      steps:
#        - task:
#            name: infrastructure-update-helm-chart-dep
#          vars:
#            chartName: ingress-nginx
#            chartRepo: https://charts.bitnami.com/bitnami
#            chartDir: qa/ingress-nginx
#        - task:
#            name: infrastructure-update-helm-chart-dep
#          vars:
#            chartName: cert-manager
#            chartRepo: https://charts.jetstack.io
#            chartDir: qa/cert-manager
#        - task:
#            name: infrastructure-update-helm-chart-dep
#          vars:
#            chartName: longhorn
#            chartRepo: https://charts.longhorn.io
#            chartDir: qa/longhorn
