apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clusterName }}-test
  namespace: {{ .Values.targetNamespace | default "default" }}
data:
  cluster: {{ .Values.clusterName }}
  nodes: "{{ len .Values.nodes }}"