{{- if .Values.l2AnnouncementPolicy.enabled }}
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: {{ .Values.l2AnnouncementPolicy.name }}
spec:
  loadBalancerIPs: {{ .Values.l2AnnouncementPolicy.loadBalancerIPs }}
  externalIPs: {{ .Values.l2AnnouncementPolicy.externalIPs }}
  interfaces:
  {{- range .Values.l2AnnouncementPolicy.interfaces }}
    - {{ . | quote }}
  {{- end }}
{{- end }}
