apiVersion: v2
name: cilium
description: cilium cni and network security for kubernetes
type: application
version: 0.1.0
appVersion: "1.18.1"

dependencies:
  - name: cilium
    version: 1.19.6
    repository: https://helm.cilium.io/
