apiVersion: v2
name: godaddy-webhook
description: A Helm chart for deploying godaddy-webhook in Kubernetes
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: godaddy-webhook
    repository: https://snowdrop.github.io/godaddy-webhook
    version: 0.5.0
