---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubevirt/kubevirt/releases/latest/download/kubevirt-operator.yaml
  - ./kubevirt-cr.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/latest/cdi-operator.yaml
  - ./cdi-cr-v1.60.2.yaml
